# Generated by Django 5.2 on 2025-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(default='', max_length=60)),
                ('state_name', models.CharField(default='', max_length=2)),
                ('campus_id', models.IntegerField(default='')),
            ],
            options={
                'verbose_name_plural': 'University Campus',
            },
        ),
    ]
